# Generated by Django 4.1.7 on 2023-03-13 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_food_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
