# Generated by Django 4.1.7 on 2023-06-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_remove_food_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='publisher_name',
            field=models.CharField(max_length=250),
        ),
    ]
